apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: moc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: snapscheduler
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: snapscheduler-2.1.0
  name: moc-snapscheduler
  namespace: snapscheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: moc
      app.kubernetes.io/name: snapscheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: moc
        app.kubernetes.io/name: snapscheduler
        backube/snapscheduler-affinity: manager
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: backube/snapscheduler-affinity
                      operator: In
                      values:
                        - manager
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: quay.io/brancz/kube-rbac-proxy:v0.11.0
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          command:
            - /manager
          image: quay.io/backube/snapscheduler:2.1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: moc-snapscheduler
      terminationGracePeriodSeconds: 10
