apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-projects
resources:
  - ../../base
  - externalsecret.yaml

configMapGenerator:
  - name: moc-project-config
    envs:
      - config.env

patches:
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: moc-projects
    path: cronjobs/moc-projects_patch.yaml
