apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-projects
resources:
  - ../../base
  - externalsecret.yaml

configMapGenerator:
  - name: moc-project-config
    envs:
      - config.env

patches:
  - path: deployments/moc_projects_patch.yaml

images:
  - name: quay.io/larsks/moc-project-tool:latest
    newTag: 96d8bd8
