apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    limits.cpu: "32"
    limits.memory: "64Gi"
    requests.cpu: "32"
    requests.memory: "64Gi"
    requests.storage: "100Gi"
