apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: netbox-api
spec:
  host: netbox.apps.ocp-staging.massopen.cloud
  path: "/api"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: netbox
    weight: 100
