apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-ingress-certificate
  namespace: openshift-ingress
spec:
  issuerRef:
    name: letsencrypt-production-dns01
    kind: ClusterIssuer
  secretName: default-ingress-certificate
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
    - '*.apps.ocp-staging.massopen.cloud'
