apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: moc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: snapscheduler
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: snapscheduler-2.1.0
  name: moc-snapscheduler
rules:
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - snapscheduler.backube
    resources:
      - snapshotschedules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - snapscheduler.backube
    resources:
      - snapshotschedules/finalizers
    verbs:
      - update
  - apiGroups:
      - snapscheduler.backube
    resources:
      - snapshotschedules/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
