apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xdmod-reader-cluster-monitor
subjects:
- kind: ServiceAccount
  name: xdmod-reader
  namespace: xdmod-tzumainn
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
