apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ingress-letsencrypt-staging
  namespace: openshift-ingress
spec:
  acme:
    email: ops@list.massopen.cloud
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - selector:
          dnsZones:
            - "ocp-prod.massopen.cloud"
        dns01:
          cnameStrategy: Follow
          route53:
            region: us-east-1
            accessKeyID: AKIAYLUGMT7YARAARH6F
            hostedZoneID: Z04486682XFINHTESP6B9
            secretAccessKeySecretRef:
              name: aws-route53-secret
              key: aws_secret_access_key
