apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    limits.cpu: "12"
    limits.memory: "32Gi"
    requests.cpu: "12"
    requests.memory: "32Gi"
    requests.storage: "200Gi"
