# Source: kubernetes-external-secrets/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
    name: moc-kubernetes-external-secrets
    labels:
        app.kubernetes.io/name: kubernetes-external-secrets
        helm.sh/chart: kubernetes-external-secrets-8.3.0
        app.kubernetes.io/instance: moc
        app.kubernetes.io/managed-by: Helm
spec:
    selector:
        app.kubernetes.io/name: kubernetes-external-secrets
    ports:
        - protocol: TCP
          port: 3001
          name: prometheus
          targetPort: prometheus
