apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
spec:
  destination:
    name: ocp-staging
    namespace: open-cluster-management-agent
  project: mocops
  source:
    path: netbox/overlays/ocp-staging
    repoURL: https://github.com/CCI-MOC/moc-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - ApplyOutOfSyncOnly=true
