apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
spec:
  template:
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
          ports:
            - containerPort: 8081
              name: netbox-auth
          envFrom:
            - configMapRef:
                name: oauth2-config
            - secretRef:
                name: oauth2-secret
