apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
spec:
  template:
    spec:
      containers:
        - name: netbox
          image: 'quay.io/hakasapl/netbox-moc-plugins:latest'
          volumeMounts:
            - name: netbox-plugin-config
              mountPath: /etc/netbox/config/plugins.py
              subPath: plugins.py
        - name: netbox-worker
          image: 'quay.io/hakasapl/netbox-moc-plugins:latest'
          volumeMounts:
            - name: netbox-plugin-config
              mountPath: /etc/netbox/config/plugins.py
              subPath: plugins.py
        - name: netbox-housekeeping
          image: 'quay.io/hakasapl/netbox-moc-plugins:latest'
          volumeMounts:
            - name: netbox-plugin-config
              mountPath: /etc/netbox/config/plugins.py
              subPath: plugins.py
      volumes:
        - name: netbox-plugin-config
          configMap:
            name: netbox-plugin-config
