apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: coldfront-secrets
spec:
  backendType: secretsManager
  data:
    - key: cluster/ocp-staging/coldfront/sso_client_id
      name: OIDC_RP_CLIENT_ID
    - key: cluster/ocp-staging/coldfront/sso_client_secret
      name: OIDC_RP_CLIENT_SECRET
    - key: cluster/ocp-staging/acct-mgt/admin_password
      name: OPENSHIFT_OCP_STAGING_PASSWORD
    - key: cluster/ocp-staging/coldfront/django_secret_key
      name: SECRET_KEY
    - key: cluster/ocp-staging/coldfront/keycloak_user
      name: KEYCLOAK_USER
    - key: cluster/ocp-staging/coldfront/keycloak_pass
      name: KEYCLOAK_PASS
