apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coldfront

resources:
  - ../../base
  - configmap.yaml
  - externalsecret.yaml
  - postgrescluster.yaml
  - route.yaml
patchesStrategicMerge:
  - patches/deployments/coldfront-deployment.yaml
  - patches/deployments/coldfront-qcluster-deployment.yaml
