apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: moc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: snapscheduler
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: snapscheduler-2.1.0
  name: moc-snapscheduler-leader-election
  namespace: snapscheduler
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
