apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: netbox-secret
spec:
  backendType: secretsManager
  data:
    - key: cluster/ocp-prod/netbox/secret_key
      name: SECRET_KEY
