apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: oauth2-secret
spec:
  backendType: secretsManager
  data:
    - key: cluster/ocp-prod/netbox/sso-clientsecret-moc
      name: OAUTH2_PROXY_CLIENT_SECRET
    - key: cluster/ocp-prod/netbox/oauth2-cookie-secret
      name: OAUTH2_PROXY_COOKIE_SECRET
