# permissions for end users to view reports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: curator-report-viewer
rules:
- apiGroups:
  - batch.curator.openshift.io
  resources:
  - reports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.curator.openshift.io
  resources:
  - reports/status
  verbs:
  - get
