apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
  - type: Container
    default:
      cpu: "4"
      memory: "16Gi"
      nvidia.com/gpu: 0
    defaultRequest:
      cpu: "4"
      memory: "16Gi"
      nvidia.com/gpu: 0
    max:
      cpu: 8
      memory: "32Gi"
      nvidia.com/gpu: 1
