apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: aws-route53-secret
  namespace: openshift-ingress
spec:
  backendType: secretsManager
  data:
    - key: cluster/ocp-prod/letsencrypt/aws_access_key_id
      name: aws_access_key_id
    - key: cluster/ocp-prod/letsencrypt/aws_secret_access_key
      name: aws_secret_access_key
