apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: moc-sso-client-secret
  namespace: openshift-config
spec:
  backendType: secretsManager
  data:
    - key: cluster/ocp-prod/moc-sso/clientsecret
      name: clientSecret
