apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: netbox
spec:
  postgresVersion: 13
  instances:
    - name: pgha1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: netbox
                  postgres-operator.crunchydata.com/instance-set: pgha1
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pgbackrest-s3-conf
      global:
        # Note that retention-type defaults to "count", so a value of "7"
        # here means "keep 7 full backups".
        #
        # https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-full-type
        repo1-retention-full: "5"
        repo2-retention-full: "4"
        repo2-s3-uri-style: path
      repos:
      - name: repo1
        schedules:
          full: '17 1 * * *'
          incremental: '17 */4 * * *'
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 15Gi
      - name: repo2
        schedules:
          full: '23 1 1 * *'
          differential: '23 3 * * 1'
          incremental: '23 5 * * *'
        s3:
          # see https://github.com/CrunchyData/postgres-operator/issues/2836
          endpoint: "rgw-j-vip.int.massopen.cloud:443"
          bucket: netbox-backup
          region: default
