apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: moc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: snapscheduler
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: snapscheduler-2.1.0
  name: moc-snapscheduler-metrics
  namespace: snapscheduler
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    app.kubernetes.io/instance: moc
    app.kubernetes.io/name: snapscheduler
