apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/core/namespaces/metallb-system/
  - ../../base/operators.coreos.com/operatorgroups/metallb/
  - ../../base/operators.coreos.com/subscriptions/metallb/
