apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: pgbackrest-s3-conf
spec:
  backendType: secretsManager
  data:
    - key: cluster/ocp-prod/netbox/netbox-backup
      name: creds_json
  template:
    stringData:
      s3.conf: |
        [global]
        repo2-s3-key=<%= JSON.parse(data.creds_json).AWS_ACCESS_KEY_ID %>
        repo2-s3-key-secret=<%= JSON.parse(data.creds_json).AWS_SECRET_ACCESS_KEY %>
