apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: acct-mgt-secrets
spec:
  backendType: secretsManager
  data:
    - key: cluster/ocp-staging/acct-mgt/admin_password
      name: ACCT_MGT_ADMIN_PASSWORD
