apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
    name: postgresql
spec:
    replicas: 1
    selector:
    name: postgresql
    strategy:
    type: Recreate
    template:
    metadata:
        labels:
        name: postgresql
    spec:
        containers:
        - env:
            - name: POSTGRES_USER
                value: <user-name>
            - name: POSTGRES_PASSWORD
                value: <password>
            - name: POSTGRES_DB
                value: <database-name>
            - name: PGDATA
                value: /var/lib/postgresql/data/pgdata
            image: "quay.io/leihaochen/curator-postgresql-extension:13"
            imagePullPolicy: IfNotPresent
#              livenessProbe:
#                exec:
#                  command:
#                    - /usr/libexec/check-container
#                    - --live
#                initialDelaySeconds: 120
#                timeoutSeconds: 10
            name: postgresql
            ports:
            - containerPort: 5432
                protocol: TCP
#              readinessProbe:
#                exec:
#                  command:
#                    - /usr/libexec/check-container
#                initialDelaySeconds: 5
#                timeoutSeconds: 1
            resources:
            requests:
                cpu: "1"
                memory: 2Gi
            limits:
                cpu: "1"
                memory: 2Gi
            volumeMounts:
            - mountPath: /var/lib/postgresql/data
                name: postgresql-data-2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: postgresql-data-2
            persistentVolumeClaim:
            claimName: pgsql-data-2
