apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/externalsecrets.kubernetes-client.io
  - ../../base/core/namespaces/external-secrets
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/moc-kubernetes-external-secrets
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/moc-kubernetes-external-secrets-auth
  - ../../base/rbac.authorization.k8s.io/clusterroles/moc-kubernetes-external-secrets
