apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    annotations:
        rbac.authorization.kubernetes.io/autoupdate: "false"
    creationTimestamp: "2021-08-19T13:00:23Z"
    name: self-provisioners
    resourceVersion: "12695"
    uid: 3f820eb3-0858-472e-aa26-6dc2ac97277e
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: self-provisioner
subjects: []
