apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moc-projects
spec:
  destination:
    name: ocp-prod
    namespace: open-cluster-management-agent
  project: mocops
  source:
    path: moc-projects/overlays/ocp-prod
    repoURL: https://github.com/CCI-MOC/moc-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - ApplyOutOfSyncOnly=true
