apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
commonLabels:
  app: netbox

resources:
  - deployments/postgres.yaml
  - deployments/redis-cache.yaml
  - deployments/redis.yaml
  - deployments/netbox.yaml
  - persistenvolumeclaims/postgres-data.yaml
  - persistenvolumeclaims/redis-cache-data.yaml
  - persistenvolumeclaims/redis-data.yaml
  - services/netbox.yaml
  - services/postgres.yaml
  - services/redis-cache.yaml
  - services/redis.yaml
  - routes.yaml

images:
  - name: netbox
    newName: quay.io/netboxcommunity/netbox
    newTag: v3.0-ldap
