apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    component: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: docker.io/redis:6-alpine
          ports:
            - containerPort: 6379
              name: redis
          args:
            - --appendonly yes
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
