apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
    name: postgres-password
spec:
    backendType: secretsManager
    data:
        - key: cluster/ocp-prod/shaw-virtual-desktop/postgres-password
          name: POSTGRES_PASSWORD
