apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/reports.batch.curator.openshift.io
  - ../../base/core/namespaces/koku-metrics-operator
  - ../../base/core/namespaces/report-system
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/curator-manager
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/curator-oauth-proxy
  - ../../base/rbac.authorization.k8s.io/clusterroles/curator-auth-proxy
  - ../../base/rbac.authorization.k8s.io/clusterroles/curator-report-editor
  - ../../base/rbac.authorization.k8s.io/clusterroles/curator-report-manager
  - ../../base/rbac.authorization.k8s.io/clusterroles/curator-report-viewer
  - ../../base/operators.coreos.com/operatorgroups/koku-metrics-operator
  - ../../base/operators.coreos.com/subscriptions/koku-metrics-operator
