apiVersion: apps/v1
kind: Deployment
metadata:
  name: moc-kubernetes-external-secrets
spec:
  template:
    spec:
      containers:
        - name: kubernetes-external-secrets
          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_REGION
              value: us-east-1
            - name: LOG_LEVEL
              value: info
          envFrom:
            - secretRef:
                name: aws-credentials
