apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: curator-oauth-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: curator-auth-proxy
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: report-system
