apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common
  - ../../bundles/cnv
  - ../../bundles/node-labeler
  - ../../bundles/ocs
  - ../../bundles/metallb
  - ../../bundles/volsync
  - ../../bundles/acct-mgt

  - certificates/api-certificate-letsencrypt.yaml
  - certificates/default-ingress-certificate.yaml
  - clusterversions/version.yaml
  - clusterroles/xdmod-permissions/
  - clusterrolebindings/xdmod-reader-xdmod-permissions
  - configmaps/admin-acks.yaml
  - externalsecrets/sso-clientsecret-moc.yaml
  - externalsecrets/sso-clientsecret-moc-testing.yaml
  - externalsecrets/rook-ceph-external-cluster-details.yaml
  - hyperconverged/kubevirt-hyperconverged.yaml
  - nodenetworkconfigurationpolicies/ceph-client-network.yaml
  - groups/xdmod-admins.yaml
  - rolebindings/xdmod-admins.yaml
  - rolebindings/xdmod-tzumainn-admins.yaml

patches:
  - path: apiservers/cluster_patch.yaml
  - path: oauths/cluster_patch.yaml
  - path: groups/local-cluster-admins.yaml

  - target:
      kind: ClusterIssuer
      name: letsencrypt-production-dns01
    path: clusterissuers/letsencrypt-production-dns01_patch.yaml

  - target:
      kind: Subscription
      group: operators.coreos.com
    path: misc/sync-wave_patch.yaml

  - target:
      kind: Namespace
    path: misc/sync-wave_patch.yaml
