apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # please keep these items sorted
  - ../../base/config.openshift.io/oauths/cluster
  - ../../bundles/external-secrets
  - externalsecrets/sso-clientsecret-moc.yaml

patchesStrategicMerge:
  - oauths/cluster_patch.yaml
