apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common

  - ../../bundles/nmstate
  - ../../bundles/node-labeler
  - ../../bundles/ocs

  - certificates/api-certificate-letsencrypt.yaml
  - certificates/default-ingress-certificate.yaml
  - externalsecrets/sso-clientsecret-moc.yaml
  - externalsecrets/rook-ceph-external-cluster-details.yaml
  - nodenetworkconfigurationpolicies/ceph-client-network.yaml

patches:
  - path: apiservers/cluster_patch.yaml
  - path: oauths/cluster_patch.yaml

  - target:
      kind: ClusterIssuer
      name: letsencrypt-production-dns01
    path: clusterissuers/letsencrypt-production-dns01_patch.yaml

  - target:
      kind: Subscription
      group: operators.coreos.com
    path: subscriptions/subscription-wave_patch.yaml
