apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/config.openshift.io/oauths/cluster
  - ../../bundles/cert-manager
  - ../../bundles/external-secrets

  - apiservers/cluster.yaml
  - certificates/api-certificate-letsencrypt.yaml
  - certificates/default-ingress-certificate.yaml
  - externalsecrets/sso-clientsecret-moc.yaml

patches:
  - path: oauths/cluster_patch.yaml

  - target:
      kind: ClusterIssuer
      name: letsencrypt-production-dns01
    path: clusterissuers/letsencrypt-production-dns01_patch.yaml

  - target:
      kind: Subscription
      group: operators.coreos.com
    path: subscriptions/subscription-wave_patch.yaml
