apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
      - "api.ocp-prod.massopen.cloud"
      servingCertificate:
        name: "api-certificate-letsencrypt"
