apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
  namespace: metallb-system
spec:
  channel: "4.9"
  name: metallb-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
