apiVersion: batch/v1
kind: CronJob
metadata:
  name: moc-projects
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: moc-project-maker
          containers:
            - name: moc-projects
              image: quay.io/larsks/moc-project-tool:latest
              volumeMounts:
                - name: moc-project-data
                  mountPath: /data
                - name: ansible-tmp
                  mountPath: /.ansible
              env:
                - name: ANSIBLE_LOCAL_TMP
                  value: /tmp
          volumes:
            - name: moc-project-data
              persistentVolumeClaim:
                claimName: moc-project-data
            - name: ansible-tmp
              emptyDir: {}
          restartPolicy: Never
