apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/operators.coreos.com/subscriptions/ocs-operator
  - ../../base/storage.k8s.io/storageclasses/ocs-external-storagecluster-cephfs
  - ../../base/storage.k8s.io/storageclasses/ocs-external-storagecluster-ceph-rbd
  - ../../base/storage.k8s.io/storageclasses/openshift-storage.noobaa.io
