apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: netbox-storage
spec:
  additionalConfig:
    maxSize: 5G
  generateBucketName: netbox-storage
  storageClassName: openshift-storage.noobaa.io
