apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox-staging

resources:
- ../ocp-prod

patches:
- path: deployments/netbox_config_patch.yaml
- path: postgresclusters/netbox_remote-backups_patch.yaml
- path: externalsecrets/netbox-backup_patch.yaml
- path: externalsecrets/oauth2-secret_patch.yaml
- path: routes/netbox_patch.yaml
  target:
    kind: Route
    name: netbox

configMapGenerator:
  - name: netbox-plugin-config
    files:
      - config/plugins.py
  - name: oauth2-config
    behavior: merge
    envs:
      - config/oauth2.env
