prometheusK8s:
  volumeClaimTemplate:
    spec:
      storageClassName: ocs-external-storagecluster-ceph-rbd
      resources:
        requests:
          storage: 50Gi
alertmanagerMain:
  volumeClaimTemplate:
    spec:
      storageClassName: ocs-external-storagecluster-ceph-rbd
      resources:
        requests:
          storage: 20Gi
