# permissions for end users to edit fetchdata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: curator-operator-fetchdata-editor-role
rules:
- apiGroups:
  - curator.operatefirst.io
  resources:
  - fetchdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - curator.operatefirst.io
  resources:
  - fetchdata/status
  verbs:
  - get
