apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-data-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-provisioner
  volumeMode: Filesystem

