apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
  - type: Container
    default:
      cpu: "4"
      memory: "8Gi"
    defaultRequest:
      cpu: "4"
      memory: "8Gi"
    max:
      cpu: 8
      memory: "16Gi"
