apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ceph-client-network-enp4s0f0np1
spec:
  parallel: true
  nodeSelector:
    storage-interface: enp4s0f0np1
  desiredState:
    interfaces:
      - name: enp4s0f0np1.250
        description: ceph client network
        type: vlan
        state: up
        vlan:
          base-iface: enp4s0f0np1
          id: 250
        ipv4:
          enabled: true
          dhcp: true
---
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ceph-client-network-ens3f0
spec:
  parallel: true
  nodeSelector:
    storage-interface: ens3f0
  desiredState:
    interfaces:
      - name: ens3f0.250
        description: ceph client network
        type: vlan
        state: up
        vlan:
          base-iface: ens3f0
          id: 250
        ipv4:
          enabled: true
          dhcp: true
---
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ceph-client-network-eno2
spec:
  parallel: true
  nodeSelector:
    storage-interface: eno2
  desiredState:
    interfaces:
      - name: eno2.250
        description: ceph client network
        type: vlan
        state: up
        vlan:
          base-iface: eno2
          id: 250
        ipv4:
          enabled: true
          dhcp: true
---
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ceph-client-network-enp4s0f1
spec:
  parallel: true
  nodeSelector:
    storage-interface: enp4s0f1
  desiredState:
    interfaces:
      - name: enp4s0f1.250
        description: ceph client network
        type: vlan
        state: up
        vlan:
          base-iface: enp4s0f1
          id: 250
        ipv4:
          enabled: true
          dhcp: true
