apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: fast-4.9
  clusterID: 8986816a-6a42-4815-a5dd-e2f3e7eac95c
  desiredUpdate:
    version: 4.9.6
    image: quay.io/openshift-release-dev/ocp-release@sha256:c9f58ccb8a9085df4eeb23e21ca201d4c7d39bc434786d58a55381e13215a199
