apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: fast-4.9
  clusterID: 8986816a-6a42-4815-a5dd-e2f3e7eac95c
  desiredUpdate:
    version: 4.8.19
    image: quay.io/openshift-release-dev/ocp-release@sha256:ac19c975be8b8a449dedcdd7520e970b1cc827e24042b8976bc0495da32c6b59
