name: Run pre-commit checks

on:
  pull_request:
  push:

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.9'

      - name: Configure caching
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: precommit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install requirements
        run: |
          pip install -r test-requirements.txt

      - name: Run linters
        run: |
          pre-commit run --all-files

  run-validation:
    runs-on: ubuntu-latest
    needs: run-linters
    container:
      image: quay.io/massopencloud/k8s-tools:2099eaa
    env:
      TERM: xterm-256color
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Run validations
        run: |
          ./ci/validate-manifests.sh

      - name: Diff with target
        run: |
          # This is meant to be strictly informative:
          # failures here should never result in a CI failure.

          if [ -n "$GITHUB_BASE_REF" ]; then
            git fetch origin ${GITHUB_BASE_REF}:target
          else
            git branch target HEAD^
          fi

          ./ci/diff-all-with-previous.sh -r target || exit 0
