apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
spec:
  template:
    spec:
      containers:
        - name: netbox
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: dbname
          envFrom:
            - secretRef:
                name: netbox-secret
            - secretRef:
                name: netbox-storage
            - configMapRef:
                name: netbox-storage
          volumeMounts:
            - name: netbox-config
              mountPath: /etc/netbox/config/extra.py
              subPath: extra.py
            - name: netbox-plugin-config
              mountPath: /etc/netbox/config/plugins.py
              subPath: plugins.py
        - name: netbox-worker
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: dbname
          envFrom:
            - secretRef:
                name: netbox-secret
            - secretRef:
                name: netbox-storage
            - configMapRef:
                name: netbox-storage
          volumeMounts:
            - name: netbox-config
              mountPath: /etc/netbox/config/extra.py
              subPath: extra.py
            - name: netbox-plugin-config
              mountPath: /etc/netbox/config/plugins.py
              subPath: plugins.py
        - name: netbox-housekeeping
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: netbox-pguser-netbox
                  key: dbname
          envFrom:
            - secretRef:
                name: netbox-secret
            - secretRef:
                name: netbox-storage
            - configMapRef:
                name: netbox-storage
          volumeMounts:
            - name: netbox-config
              mountPath: /etc/netbox/config/extra.py
              subPath: extra.py
            - name: netbox-plugin-config
              mountPath: /etc/netbox/config/plugins.py
              subPath: plugins.py
      initContainers:
        - name: set-bucket-policy
          image: docker.io/amazon/aws-cli:latest
          envFrom:
            - secretRef:
                name: netbox-storage
            - configMapRef:
                name: netbox-storage
          volumeMounts:
            - name: netbox-bucket-policy
              mountPath: /policy
          command:
            - bash
            - -c
            - |
              sed "s/BUCKET_NAME/${BUCKET_NAME}/g" /policy/allow-anonymous-read.json > /tmp/policy.json
              while :; do
                aws --ca-bundle /run/secrets/kubernetes.io/serviceaccount/service-ca.crt \
                  --endpoint https://${BUCKET_HOST} s3api put-bucket-policy \
                  --bucket ${BUCKET_NAME} --policy file:///tmp/policy.json && break
                sleep 5
              done
      volumes:
        - name: netbox-config
          configMap:
            name: netbox-config
        - name: netbox-bucket-policy
          configMap:
            name: netbox-bucket-policy
        - name: netbox-plugin-config
          configMap:
            name: netbox-plugin-config
