apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xdmod-reader-xdmod-permissions
subjects:
- kind: ServiceAccount
  name: xdmod-reader
  namespace: xdmod-tzumainn
roleRef:
  kind: ClusterRole
  name: xdmod-permissions
  apiGroup: rbac.authorization.k8s.io
